//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorID { get; set; }
        public string Name { get; set; }
        public string Blood_Group { get; set; }
        public string Medical_report { get; set; }
        public string Donor_Address { get; set; }
        public string Contact_Number { get; set; }
    }
}
